apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-manage-pv
  namespace: ingsoft
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/config-manage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-manage-pvc
  namespace: ingsoft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
